all:test1-1 test1-2 test1-3
	
test1-1:test1-1.c
	gcc -o test1-1 test1-1.c

test1-2:test1-2.c
	gcc -o test1-2 test1-2.c

test1-3:test1-3.c
	gcc -o test1-3 test1-3.c

clean:
	rm test1-1 test1-2 test1-3
